# product-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          ports:
            - containerPort: 8082
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: user-db-secrets  # Or db-config if using ConfigMap
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-db-secrets  # Or db-config if using ConfigMap
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secrets  # Or db-config if using ConfigMap
                  key: DB_PASSWORD
            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: eurekaUrl
            - name: APPLICATION_NAME
              value: "userservice"
            - name: SERVER_PORT
              value: "8082"
            - name: HOST
              value: "adena.local"
